spring:
  profiles:
    active: local # 기본 환경 선택
---
server:
  port: 8082

spring:
  profiles: local
  datasource:
    data: classpath:data.sql # 시작할때 실행시킬 script
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true